In [1]:
import numpy as np
i = 10
a = np.zeros(shape=(i,i))
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [6]:
stations = [0,65,93,36]

In [7]:
points = []
for s in stations:
    s = str(s)
    if len(s)==1:
        s = s*2
    points.append([int(s[0]),int(s[1])])
print(points)

[[0, 0], [6, 5], [9, 3], [3, 6]]


In [9]:
i=1
for x,y in points:
    a[x,y] = i
    i+=1

In [10]:
a

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 4., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 2., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 3., 0., 0., 0., 0., 0., 0.]])

In [11]:
import itertools
from scipy.spatial.distance import cdist

a = np.asarray(a, dtype=np.int) 
n = m.max()
indexes = []
for k in range(1, n+1):
    tmp = np.nonzero(m == k)
    tmp = np.asarray(tmp).T
    indexes.append(tmp)

In [30]:
list(itertools.combinations(range(n), 2))

[(0, 1), (0, 2), (0, 3), (1, 2), (1, 3), (2, 3)]

In [26]:
distance_matrix = np.zeros((n, n), dtype=np.float)   
for i, j in itertools.combinations(range(n), 2):
    print(indexes[i].shape)
    print(indexes[i])
    d2 = cdist(indexes[i], indexes[j], metric='cityblock') 
    #distance_matrix[i, j] = distance_matrix[j, i] = d2.min()

(1, 2)
[[0 0]]
(1, 2)
[[0 0]]
(1, 2)
[[0 0]]
(1, 2)
[[6 5]]
(1, 2)
[[6 5]]
(1, 2)
[[9 3]]


In [21]:
distance_matrix

array([[ 0., 11., 12.,  9.],
       [11.,  0.,  5.,  4.],
       [12.,  5.,  0.,  9.],
       [ 9.,  4.,  9.,  0.]])